----- JOINS -----


USE TEST;

SELECT * FROM EMPC;

SELECT * FROM EMPSC;

SELECT EMPC.EID, EMPC.NAME, EMPC.CITY, EMPC.DOJ, EMPSC.DEPT, EMPSC.SALARY
FROM EMPC
INNER JOIN EMPSC
ON EMPC.EID = EMPSC.EID;

SELECT E1.EID, E1.NAME, E1.CITY, E1.DOJ, E2.DEPT, E2.SALARY
FROM EMPC E1
INNER JOIN EMPSC E2
ON E1.EID = E2.EID;

SELECT EMPC.EID, NAME, CITY, DOJ, DEPT, SALARY
FROM EMPC
INNER JOIN EMPSC
ON EMPC.EID = EMPSC.EID;


SELECT E1.EID, E1.NAME, E1.CITY, E1.DOJ, E2.DEPT, E2.DESI, E2.SALARY
FROM EMPC E1
LEFT JOIN EMPSC E2
ON E1.EID = E2.EID;

SELECT E1.EID, E1.NAME, E1.CITY, E1.DOJ, E2.DEPT, E2.DESI, E2.SALARY
FROM EMPC E1
RIGHT JOIN EMPSC E2
ON E1.EID = E2.EID;


--------- CROSS JOIN ----------

CREATE TABLE CJ1
(
RNO CHAR(2),
NAME VARCHAR (10),
)

INSERT INTO CJ1 VALUES
('1', 'KAPIL'),
('2', 'ROHAN'),
('3', 'RAJAT'),
('4', 'AMIT'),
('5', 'MOHIT');

CREATE TABLE CJ2
(
RNO CHAR (2),
MARKS INT
)

INSERT INTO CJ2 VALUES
('1', 90),
('2', 95),
('3', 80),
('10', 79),
('11', 94);

SELECT * FROM CJ1;
SELECT * FROM CJ2;

SELECT CJ1.RNO, CJ1.NAME, CJ2.MARKS
FROM CJ1
CROSS JOIN CJ2;

SELECT CJ1.RNO, CJ1.NAME, CJ2.MARKS
FROM CJ1
CROSS JOIN CJ2
WHERE CJ1.RNO = CJ2.RNO;

----- SELF JOIN -----

CREATE TABLE BOSS
(
ID CHAR(1),
NAME CHAR(1),
BOSSID CHAR(1)
)

INSERT INTO BOSS VALUES
('1', 'A', NULL),
('2', 'B', '1'),
('3', 'C', '1'),
('4', 'D', '2'),
('5', 'E', '3'),
('6', 'F', '3'),
('7', 'G', '6');

SELECT * FROM BOSS;

CREATE TABLE BOSNO
(
BID CHAR(1),
NAME CHAR(1)
)

INSERT INTO BOSNO VALUES
('1', 'A'),
('2', 'B'),
('3', 'C'),
('6', 'F');

SELECT * FROM BOSNO;
SELECT * FROM BOSS;

SELECT BOSS.ID, BOSS.NAME, BOSNO.NAME AS 'BOSS NAME'
FROM BOSS
LEFT JOIN BOSNO
ON BOSS.BOSSID = BOSNO.BID;

SELECT * FROM BOSS;

SELECT S1.ID, S1.NAME, S2.NAME
FROM BOSS S1
LEFT JOIN BOSS S2
ON S1.BOSSID = S2.ID;


----- set clauses -----


SELECT BOSS.ID, BOSS.NAME, BOSNO.NAME AS 'BOSS NAME'
FROM BOSS
LEFT JOIN BOSNO
ON BOSS.BOSSID = BOSNO.BID

UNION

SELECT S1.ID, S1.NAME, S2.NAME AS 'BOSS NAME'
FROM BOSS S1
LEFT JOIN BOSS S2
ON S1.BOSSID = S2.ID;

SELECT BOSS.ID, BOSS.NAME, BOSNO.NAME AS 'BOSS NAME'
FROM BOSS
LEFT JOIN BOSNO
ON BOSS.BOSSID = BOSNO.BID

UNION ALL

SELECT S1.ID, S1.NAME, S2.NAME AS 'BOSS NAME'
FROM BOSS S1
LEFT JOIN BOSS S2
ON S1.BOSSID = S2.ID;


SELECT BOSS.ID, BOSS.NAME, BOSNO.NAME AS 'BOSS NAME'
FROM BOSS
LEFT JOIN BOSNO
ON BOSS.BOSSID = BOSNO.BID

INTERSECT

SELECT S1.ID, S1.NAME, S2.NAME AS 'BOSS NAME'
FROM BOSS S1
LEFT JOIN BOSS S2
ON S1.BOSSID = S2.ID;

