USE TEST;

CREATE FUNCTION CORPMAIL(@I CHAR(5), @N VARCHAR(20), @D VARCHAR(20))
RETURNS VARCHAR(50)
AS
BEGIN

	DECLARE @S AS INT
	DECLARE @L AS INT
	DECLARE @LN AS VARCHAR(20)
	DECLARE @FN AS VARCHAR(20)
	DECLARE @EM AS VARCHAR(50)
	SET @S = CHARINDEX(' ',@N)
	SET @L = LEN(@N)
	SET @LN = RIGHT(@N, @L - @S)
	SET @FN = LEFT(@N, @S)
	SET @EM = CONCAT(@FN, '.', @LN, RIGHT(@I, 4), @D, '.COM')
	RETURN @EM

END;

SELECT * FROM EMPC;
SELECT * FROM EMPSC;

SELECT UPPER(CONCAT(LEFT(NAME, CHARINDEX(' ', NAME)),
'.',RIGHT(NAME, LEN(NAME) - CHARINDEX(' ', NAME)),
'@OUTLOOK.COM'))
FROM EMPC;

SELECT DBO.CORPMAIL('E0001', 'VISHAL SHIVNANI', 'OUTLOOK');

SELECT EID, NAME, DBO.CORPMAIL(EID, NAME, 'OUTLOOK') AS 'CORPMAIL'
FROM EMPC;


------------------- PROCEDURE ---------------

CREATE PROCEDURE DEMO
AS
BEGIN
	SELECT * FROM EMPC
	WHERE CITY = 'DELHI'

END;

EXEC DEMO;

DEMO;

DROP PROCEDURE DEMO;

------------------------ PARAMETERIZED STORE PROCEDURE ---------------------------------

CREATE PROCEDURE DEMO @S AS VARCHAR(20)
AS
BEGIN
	SELECT * FROM EMPC
	WHERE CITY = @S;
END;

DEMO 'DELHI';
DEMO 'PUNE';

---------------------------------------------------------------

CREATE PROCEDURE SHOW @T AS VARCHAR(20)
AS
BEGIN
	EXEC('SELECT * FROM '+ @T);
END;

SHOW 'EMPC';


------------------------------ PROCEDURE FOR DATA MANIPULATION -------------

CREATE PROCEDURE INSER @E AS CHAR(5), @N AS VARCHAR(20), @A1 AS VARCHAR(20), @A2 AS VARCHAR(20), 
@C AS VARCHAR(20), @P AS CHAR(15), @EM AS VARCHAR(20), @D1 AS DATE, @D2 AS DATE

AS
BEGIN
	INSERT INTO EMPC VALUES(@E, @N, @A1, @A2, @C, @P, @EM, @D1, @D2);
END;

INSER 1117, 'NITESH VAJPAI', 'HNO, 2', 'CITY CENTER', 'NOIDA', 2616454488, 'NIT.VAJ1561@YAHOO.COM', '12-JAN-23', '26-JUNE-1997';

SELECT * FROM EMPC;

DELETE FROM EMPC WHERE EID = 1117;


-----------------------------------------------------



CREATE PROCEDURE SHOW_DATA @E AS CHAR(5), @N AS VARCHAR(20), @A1 AS VARCHAR(20), @A2 AS VARCHAR(20), 
@C AS VARCHAR(20), @P AS CHAR(15), @EM AS VARCHAR(20), @D1 AS DATE, @D2 AS DATE

AS
BEGIN
	INSERT INTO EMPC VALUES(@E, @N, @A1, @A2, @C, @P, @EM, @D1, @D2);
	SELECT * FROM EMPC;
END;


SHOW_DATA 1117, 'NITESH VAJPAI', 'HNO, 2', 'CITY CENTER', 'NOIDA', 2616454488, 'NIT.VAJ1561@YAHOO.COM', '12-JAN-23', '26-JUNE-1997';

DROP PROCEDURE SHOW_DATA;

CREATE PROCEDURE SHOW_DATA @E AS CHAR(5), @N AS VARCHAR(20), @A1 AS VARCHAR(20), @A2 AS VARCHAR(20), 
@C AS VARCHAR(20), @P AS CHAR(15), @EM AS VARCHAR(20), @D1 AS DATE, @D2 AS DATE

AS
BEGIN
	INSERT INTO EMPC VALUES(@E, @N, @A1, @A2, @C, @P, @EM, @D1, @D2);
	SELECT * FROM EMPC WHERE EID = @E;
END;


SHOW_DATA 1117, 'NITESH VAJPAI', 'HNO, 2', 'CITY CENTER', 'NOIDA', 2616454488, 'NIT.VAJ1561@YAHOO.COM', '12-JAN-23', '26-JUNE-1997';


---------------------------------------------------------------------


CREATE PROCEDURE SHOW_DATA @E AS CHAR(5), @N AS VARCHAR(20), @A1 AS VARCHAR(20), @A2 AS VARCHAR(20), 
@C AS VARCHAR(20), @P AS CHAR(15), @EM AS VARCHAR(20), @D1 AS DATE, @D2 AS DATE, @DE AS VARCHAR (20), @DES AS VARCHAR(20), @SAL AS INT

AS
BEGIN

	INSERT INTO EMPC VALUES(@E, @N, @A1, @A2, @C, @P, @EM, @D1, @D2);
	INSERT INTO EMPSC VALUES(@E, @DE, @DES, @SAL);
	SELECT * FROM EMPC WHERE EID = @E;
	SELECT * FROM EMPSC WHERE EID = @E;

END;


SHOW_DATA 1117, 'NITESH VAJPAI', 'HNO, 2', 'CITY CENTER', 'NOIDA', 2616454488, 'NIT.VAJ1561@YAHOO.COM', '12-JAN-23', '26-JUNE-1997', 'ADMIN', 'ACCOUNTANT', 598748;

DROP PROCEDURE SHOW_dATA;

-----------------------------------------------------------------------------------------------------

CREATE PROCEDURE SHOW_DATA @E AS CHAR(5), @N AS VARCHAR(20), @A1 AS VARCHAR(20), @A2 AS VARCHAR(20), 
@C AS VARCHAR(20), @P AS CHAR(15), @EM AS VARCHAR(20), @D1 AS DATE, @D2 AS DATE, @DE AS VARCHAR (20), @DES AS VARCHAR(20), @SAL AS INT

AS
BEGIN

	INSERT INTO EMPC VALUES(@E, @N, @A1, @A2, @C, @P, @EM, @D1, @D2);
	INSERT INTO EMPSC VALUES(@E, @DE, @DES, @SAL);
	SELECT * FROM EMPC WHERE EID = @E;
	SELECT * FROM EMPSC WHERE EID = @E;

	SELECT EMPC.EID, NAME, CITY, DOJ, DEPT, DESI, SALARY AS 'BASIC', SALARY * 0.15 AS 'HRA', SALARY * 0.09 AS 'PF'
	FROM EMPC
	INNER JOIN EMPSC
	ON EMPC.EID = EMPSC.EID
	WHERE EMPC.EID = @E;

END;


SHOW_DATA 1117, 'NITESH VAJPAI', 'HNO, 2', 'CITY CENTER', 'NOIDA', 2616454488, 'NIT.VAJ1561@YAHOO.COM', '12-JAN-23', '26-JUNE-1997', 'ADMIN', 'ACCOUNTANT', 598748;







---------------------------------------------- ASSIGNMENT 8 -----------------------------------------------------

USE INVENTORY;

SELECT * FROM SUPPLIER;

CREATE PROCEDURE ADDSUPPLIER @S AS CHAR(5), @N AS VARCHAR(20), @A AS VARCHAR(30), @C AS VARCHAR(20), @P AS CHAR(15), @EM AS VARCHAR(20)
AS
BEGIN

	INSERT INTO SUPPLIER VALUES(@S, @N, @A, @C, @P, @EM)
	SELECT * FROM SUPPLIER
	WHERE SID = @S;
END;

ADDSUPPLIER S5001, 'NISCHAY YADAV', 'SECTOR 2', 'SIRSA', 69849616516, 'NISHC@YAHOO.COM'; 

DELETE FROM SUPPLIER WHERE SID = 'S5001';

------------------------------------------------------------------------------------------------

SELECT * FROM PRODUCT;

CREATE PROCEDURE ADDPRO @P AS CHAR(5), @PD AS VARCHAR(20), @PR AS INT, @C AS CHAR(2), @S AS CHAR(5)
AS
BEGIN

	INSERT INTO PRODUCT VALUES(@P, @PD, @PR, @C, @S)
	SELECT * FROM PRODUCT
	WHERE PID = @P;

END;

ADDPRO P5001, 'IPHONE', 120054, 'IT', S5001;

DELETE FROM PRODUCT WHERE PID = 'P5001';

------------------------------------------------------------------------------------

SELECT * FROM CUST;

CREATE PROCEDURE ADDCUST @C AS CHAR(5), @N AS VARCHAR(20), @A AS VARCHAR(20), @CI AS VARCHAR(10), @P AS CHAR(15), @E AS VARCHAR(20), @D AS DATE
AS
BEGIN

	INSERT INTO CUST VALUES(@C, @N, @A, @CI, @P, @E, @D)
	SELECT * FROM CUST WHERE CID = @C;

END;

ADDCUST 'C0011', 'RAM BAJAJ', '1/3 MANDIR ROAD', 'AYODHYA', 6663261848, 'RAM.BAJ@YAHOO.COM', '25-DEC-1998';

DELETE FROM CUST WHERE CID = 'C0011';

----------------------------------------------------------------------------------------------------------

SELECT * FROM ORDERS;

CREATE PROCEDURE ADDORDER @O AS CHAR(5), @D AS DATETIME,  @P AS CHAR(5), @C AS CHAR(5), @Q AS INT
AS
BEGIN
	
	SET @D = CONVERT(date, GETDATE());
	INSERT INTO ORDERS VALUES(@O, @D, @P, @C, @Q)
	SELECT * FROM ORDERS 
	WHERE OID = @O;

END;
	
ADDORDER 'O0006', '', 'P5001', 'C0011', 30;

DELETE FROM ORDERS WHERE OID = 'O0006';

-----------------------------------------------------------------------------------------------------------------
