----- ASSIGNMENT -----


SELECT CITY, COUNT(EID) AS 'NO. OF EMPLOYEES'
FROM EMP
GROUP BY CITY
ORDER BY COUNT(EID) DESC;

SELECT CITY, COUNT(EID) AS 'NO. OF EMPLOYEES'
FROM EMP
GROUP BY CITY
ORDER BY 'NO. OF EMPLOYEES' DESC;

SELECT * FROM EMP
WHERE EMAIL NOT LIKE '%YAHOO%';

SELECT DESI, COUNT(EID) AS 'NO. OF EMPLOYEES', SUM(SALARY) AS 'TOTAL COST'
FROM EMP_SAL
GROUP BY DESI
ORDER BY 'TOTAL COST' DESC;

SELECT * FROM EMP_SAL;