USE TEST;

CREATE FUNCTION CORPMAIL(@I CHAR(5), @N VARCHAR(20), @D VARCHAR(20))
RETURNS VARCHAR(50)
AS
BEGIN

	DECLARE @S AS INT
	DECLARE @L AS INT
	DECLARE @LN AS VARCHAR(20)
	

END;

SELECT * FROM EMPC;
SELECT * FROM EMPSC;

SELECT UPPER(CONCAT(LEFT(NAME, CHARINDEX(' ', NAME)),
'.',RIGHT(NAME, LEN(NAME) - CHARINDEX(' ', NAME)),
'@OUTLOOK.COM'))
FROM EMPC;

	